#pragma once

#define SCRATCHPAD_SIZE (1 << 21)
#define SCRATCHPAD_STRIDED 0

#define REGISTERS_SIZE 256
#define INITIAL_HASH_SIZE 64
#define RANDOMX_PROGRAM_SIZE 256
#define ENTROPY_SIZE (128 + 2048)
#define COMPILED_PROGRAM_SIZE 65536
#define LOCAL_GROUP_SIZE 64
#define WORKERS_PER_HASH 64
#define HASHES_PER_GROUP (LOCAL_GROUP_SIZE / WORKERS_PER_HASH)
